# Generated by Django 3.2.9 on 2022-01-26 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0012_auto_20220125_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_key',
            field=models.ManyToManyField(blank=True, related_name='dislike_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
