# Generated by Django 3.2.9 on 2022-01-28 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_auto_20220128_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user_key',
            field=models.ManyToManyField(related_name='user_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
