# Generated by Django 3.2.9 on 2022-01-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_group_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
