# Generated by Django 3.2.9 on 2022-01-30 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0022_auto_20220130_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupJointRequest',
            new_name='GroupJoinRequest',
        ),
    ]
